# Docker Configuration for TweetKar
version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: tweetkar_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: tweetkar
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - tweetkar_network

  # Backend API
  backend:
    build: ./backend
    container_name: tweetkar_backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/tweetkar?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_change_this
      JWT_EXPIRE: 30d
      CLIENT_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - tweetkar_network
    command: npm run dev

  # Frontend
  frontend:
    build: ./frontend
    container_name: tweetkar_frontend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - tweetkar_network
    command: npm start

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  tweetkar_network:
    driver: bridge
